### ISSUE TITLE
Error services.yml

### ISSUE THREAD

**Issue by nan-guo** [aivus/SonataMediaFixedDimensionsResizer#1]
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 4 (near " arguments: [@sonata.media.adapter.image.gd, 'inset', @sonata.media.metadata.proxy]").

**Comment by aivus** [comment]
Hi @nan-guo.

Feel free to create a PR and I'll merge it.

**Comment by aivus** [comment]
fixed in #2
